Section 2
gsg-K1-FC/project5 pull request #6
Opened 2020-10-12 19:04 UTC by sondos-zaro

create a section-2 in landing-page
 the following element naming "class-name" used in the section  
 the section contains( img,button,h2,h3,p,div) elements

2020-10-12 21:03 UTC, Rahaf-96 requested changes
Great job Sondos!! :partying_face:  I left some comments on the things that you should change. 
Also, you should work more on responsive design.

2020-10-12 21:03 UTC, Rahaf-96 commented on style.css
> +    /* width: 100%; */
you shouldn't push code that doesn't work

2020-10-12 21:03 UTC, Rahaf-96 commented on style.css
> +span {
give the span a class name instead of giving the element itself a style, because if there was another span on the same page it will take the same style.

2020-10-12 21:03 UTC, Rahaf-96 commented on style.css
> +    list-style: none;
This property is not necessary. notice that it's for a list element, not a button,

2020-10-13 08:19 UTC, saharAdem commented
Great Sondos. However, It's better to create a folder for all images and put them inside it.

2020-10-14 18:40 UTC, saharAdem approved these changes

2020-10-14 18:40 UTC, Rahaf-96 approved these changes
Great Job!

2020-10-14 18:41 UTC, merged